In [80]:
from bs4 import BeautifulSoup
import requests
import re

Question 1

In [120]:
def wikiheader(url):
    header=[]
    page=requests.get(url)
    soup=BeautifulSoup(page.content)
    for h in soup.find_all('span',class_="mw-headline"):
        header.append(h.text)
    df=pd.DataFrame({'Headers':header})
    return df

In [121]:
wikiheader('https://en.wikipedia.org/wiki/Main_Page')

                         Headers
0           Welcome to Wikipedia
1  From today's featured article
2               Did you know ...
3                    In the news
4                    On this day
5       Today's featured picture
6       Other areas of Wikipedia
7    Wikipedia's sister projects
8            Wikipedia languages

Question 2

In [81]:
def imbd100movies(url):
    page=requests.get(url)
    name=[]
    rating=[]
    year=[]
    soup=BeautifulSoup(page.content)
    for n in soup.find_all('h3',class_="lister-item-header"):
        name.append(re.sub('[()0-9.\n]+','',n.text))
    for r in soup.find_all('div',class_="ipl-rating-star small"):
        rating.append(re.sub('\n','',r.text))
    for y in soup.find_all('span',class_="lister-item-year text-muted unbold"):
        year.append(re.sub('[()]','',y.text))
    df=pd.DataFrame({'Name':name,'Ratings':rating,'Year_of_Release':year},index=range(1,101))
    return df

In [82]:
url='https://www.imdb.com/list/ls091520106/'
imbd100movies(url)

                                    Name Ratings Year_of_Release
1               The Shawshank Redemption     9.3            1994
2                          The Godfather     9.2            1972
3                  The Godfather Part II       9            1974
4                        The Dark Knight       9            2008
5                              Angry Men       9            1957
..                                   ...     ...             ...
96                    North by Northwest     8.3            1959
97                    A Clockwork Orange     8.3            1971
98                                Snatch     8.2            2000
99   Le fabuleux destin d'Amélie Poulain     8.3            2001
100                              The Kid     8.2            1921

[100 rows x 3 columns]

Question 3

In [179]:
def delhirestaurents(url):
    name=[]
    cuisine=[]
    loc=[]
    rating=[]
    images=[]
    page=requests.get(url)
    soup=BeautifulSoup(page.content)
    for n in soup.find_all('div',class_="restnt-info cursor"):
        name.append(n.text)
    for c in soup.find_all('span',class_="double-line-ellipsis"):
        cuisine.append(re.sub('₹.*[|]','',c.text))
    for l in soup.find_all('div',class_="restnt-loc ellipsis"):
        loc.append(l.text)
    for r in soup.find_all('div',class_="restnt-rating rating-4"):
        rating.append(r.text)
    r1=soup.find('div',class_="restnt-rating rating-5")
    rating.insert(5,r1.text)
    rating.insert(12,r1.text)
    for i in soup.find_all('img',class_="no-img"):
        images.append(i['data-src'])
    df=pd.DataFrame({'Name':name,'Cuisine':cuisine,'Location':loc,'Rating':rating,'Images_url':images},index=range(1,22))
    return df

In [180]:
url='https://www.dineout.co.in/delhi-restaurants/welcome-back'
delhirestaurents(url)

,Name,Cuisine,Location,Rating,Images_url
1,"My Bar HeadquartersConnaught Place, Central Delhi","North Indian, Chinese","Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
2,"Berco'sConnaught Place, Central Delhi","Chinese, Thai","Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
3,"The G.T. RoadM-Block,Connaught Place, Central ...",North Indian,"M-Block,Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
4,"Punjab GrillJanpath, Central Delhi","North Indian, Mughlai","Janpath, Central Delhi",3.7,https://im1.dineout.co.in/images/uploads/resta...
5,"Unplugged CourtyardConnaught Place, Central Delhi","North Indian, Italian, Chinese, Turkish, Cont...","Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
6,"SubwayConnaught Place, Central Delhi",Fast Food,"Connaught Place, Central Delhi",5,https://im1.dineout.co.in/images/uploads/resta...
7,"LocalScindia House,Connaught Place, Central Delhi","North Indian, Asian, Continental","Scindia House,Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
8,"Kill The BillConnaught Place, Central Delhi","Fast Food, North Indian, Seafood, Chinese, Co...","Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
9,"The EmbassyConnaught Place, Central Delhi","North Indian, European, Fast Food, Italian, C...","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
10,"Gin & JulietF-Block,Connaught Place, Central D...","Italian, Chinese, North Indian, Fast Food","F-Block,Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
11,Desi Villagio - Village Theme Restro BarConnau...,North Indian,"Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
12,"Barbeque NationConnaught Place, Central Delhi","North Indian, Chinese, Beverages","Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
13,"Mughal-E-HazamConnaught Place, Central Delhi","North Indian, Mughlai","Connaught Place, Central Delhi",5,https://im1.dineout.co.in/images/uploads/resta...
14,"The HostF-Block,Connaught Place, Central Delhi","North Indian, Chinese","F-Block,Connaught Place, Central Delhi",4.2,https://im1.dineout.co.in/images/uploads/resta...
15,Ardor 2.1 Restaurant and LoungeConnaught Place...,"North Indian, Chinese, Italian, Continental","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
16,"United Coffee HouseConnaught Place, Central Delhi","European, Mediterranean, North Indian","Connaught Place, Central Delhi",4.4,https://im1.dineout.co.in/images/uploads/resta...
17,"The Junkyard CafeConnaught Place, Central Delhi","North Indian, Continental, Chinese, Fast Food","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
18,"Taco BellConnaught Place, Central Delhi","Tex Mex, Mexican","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
19,"Biryani BluesScindia House,Connaught Place, Ce...",Biryani,"Scindia House,Connaught Place, Central Delhi",4.2,https://im1.dineout.co.in/images/uploads/resta...
20,"Excuse Me BossF-Block,Connaught Place, Central...","North Indian, Chinese, Italian, Continental, ...","F-Block,Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
21,"QBAConnaught Place, Central Delhi","North Indian, Continental, Italian","Connaught Place, Central Delhi",4.2,https://im1.dineout.co.in/images/uploads/resta...

Question 4

In [217]:
def former_presidents_of_india(url):
    pname=[]
    nth=[]
    page=requests.get(url)
    soup=BeautifulSoup(page.content)
    for n in soup.find_all('div',class_="desc-sec"):
        pname.append(re.sub('\d+[A-Za-z ]+|\n','',n.text))
        o=re.search('\d+[A-Za-z ]+',n.text)
        nth.append(o.group())
    df=pd.DataFrame({'Name_of_Presidnet':pname,'In_Order_Desc':nth},index=range(1,15))
    return df

In [218]:
url='https://www.presidentofindia.gov.in/former-presidents'
former_presidents_of_india(url)

               Name_of_Presidnet            In_Order_Desc
1           Shri Ram Nath Kovind  14th President of India
2          Shri Pranab Mukherjee  13th President of India
3   Smt Pratibha Devisingh Patil  12th President of India
4         DR. A.P.J. Abdul Kalam  11th President of India
5           Shri K. R. Narayanan  10th President of India
6        Dr Shankar Dayal Sharma  9th  President of India
7            Shri R Venkataraman   8th President of India
8               Giani Zail Singh   7th President of India
9      Shri Neelam Sanjiva Reddy   6th President of India
10      Dr. Fakhruddin Ali Ahmed   5th President of India
11  Shri Varahagiri Venkata Giri   4th President of India
12              Dr. Zakir Husain   3rd President of India
13  Dr. Sarvepalli Radhakrishnan   2nd President of India
14           Dr. Rajendra Prasad   1st President of India